apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-src-sample-vol
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /var/lib/k8s/k8s-lampp-windows/2.src-deploy-disk/storage
#    path: /run/desktop/mnt/host/c/k8s/k8s-lampp-windows/2.src-deploy-disk/storage
