apiVersion: v1
kind: Service
metadata:
  name: php5-fpm-service
  labels:
    app: php5-fpm
spec:
  selector:
    app: php5-fpm
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php5-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php5-fpm
  template:
    metadata:
      labels:
        app: php5-fpm
    spec:
      containers:
      - name: php5-fpm
        image: php5-gke-php:latest
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        command:
          - sh
          - "-c"
          - |
            /usr/local/bin/dns-regist.sh && \
            php-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        securityContext:
          privileged: true
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
