apiVersion: v1
kind: Service
metadata:
  name: php7-fpm-service
  labels:
    app: php7-fpm
spec:
  selector:
    app: php7-fpm
  ports:
    - protocol: TCP
      port: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php7-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php7-fpm
  template:
    metadata:
      labels:
        app: php7-fpm
    spec:
      containers:
      - name: php7-fpm
        image: php-gke-php:latest
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        command:
          - sh
          - "-c"
          - |
            /usr/local/bin/entrypoint.sh php-fpm
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        - name: ssh-dir
          mountPath: "/mnt/ssh"
        securityContext:
          privileged: true
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
      - name: ssh-dir
        secret:
          secretName: ssh-keys
          defaultMode: 0600