apiVersion: v1
kind: Service
metadata:
  name: apache-sv
  labels:
    app: apache
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30802
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    nodePort: 30402
    targetPort: 443
    protocol: TCP
  selector:
    app: apache
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: php-gke-apache:latest
#        env:
#        - name: LC_CTYPE
#          value: ja_JP.utf8
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 10080
          initialDelaySeconds: 5
          periodSeconds: 5
        command:
        - sh
        - "-c"
        - |
          ln -s /mnt/src/example1.co.jp /home/example1.co.jp && \
          ln -s /mnt/src/example2.co.jp /home/example2.co.jp && \
          apachectl -D FOREGROUND
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        volumeMounts:
        - name: disk
          mountPath: "/mnt/src"
        securityContext:
          privileged: true
      volumes:
      - name: disk
        persistentVolumeClaim:
          claimName: php-src-sample-pvc
