apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-apache-psql-sample-vol
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hostpath
  hostPath:
    path: /var/lib/k8s/k8s-lampp-windows/1.db-disk/storage
#    path: /run/desktop/mnt/host/c/k8s/k8s-lampp-windows/1.db-disk/storage
