apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-apache-psql-sample-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
