apiVersion: v1
kind: Secret
metadata:
  name: php-apache-psql-secret
type: Opaque
data:
  database_user: ZGF0YWJhc2VfdXNlcg==
  database_password: ZGF0YWJhc2VfcGFzc3dvcmQ=
  secret_key_base: c2VjcmV0X2tleV9iYXNl
